### ISSUE TITLE
Start index flag doesn't work

### ISSUE THREAD

**Issue by dljsjr** [jeffwidman/bitbucket-issue-migration#69]
I don't know much about what's going on with this, but when I try to use `-f` I get the following:

```
Traceback (most recent call last):
  File "migrate.py", line 481, in <module>
    sys.exit(main(options))
  File "migrate.py", line 158, in main
    issues = get_issues(bb_url, options.start, options.bb_auth)
  File "migrate.py", line 217, in get_issues
    assert len(issues) == result['count']
AssertionError
```

**Comment by jeffwidman** [comment]
Good catch, I forgot to adjust the length test for when using `-f`. I'll push a fix shortly.
